FROM centos:7
RUN yum update -y && \
    yum clean all && \
    yum install -y sudo && \
    yum install epel-release -y && \
    rpm -Uvh http://rpms.famillecollet.com/enterprise/remi-release-7.rpm && \
    yum -y install --enablerepo=remi-php73 php-fpm php-pgsql php-mbstring php-pecl-apcu php-pecl-igbinary php-pecl-memcache php-pecl-memcached php-pecl-msgpack php-process php-pecl-redis php-pecl-redis php-pecl-zip php-gd php-openssl php-xml unzip php
RUN yum install -y --enablerepo=remi-php73 php-mcrypt
RUN sudo mkdir -p /run/php-fpm
COPY www.conf /etc/php-fpm.d/www.conf
COPY php.ini /etc/php.ini
ENTRYPOINT /usr/sbin/php-fpm --nodaemonize