FROM centos:7
COPY nginx.repo /etc/yum.repos.d/nginx.repo
RUN yum update -y && \
    yum clean all && \
    yum install -y nginx
COPY default.conf /etc/nginx/conf.d/default.conf
ENTRYPOINT /usr/sbin/nginx -g 'daemon off;' -c /etc/nginx/nginx.conf