FROM centos:7
ENV PATH $PATH:/usr/pgsql-11/bin
RUN yum clean all
RUN yum install -y sudo
RUN yum install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
RUN yum install -y postgresql11
RUN yum install -y postgresql11-server
RUN yum install -y epel-release
RUN yum install -y –enablerepo=epel proj proj-devel proj-epsg
RUN yum install -y –enablerepo=epel gdal gdal-devel
RUN yum install -y postgis25_11
RUN su postgres -c 'initdb -E UTF8 --no-locale -D /var/lib/pgsql/11/data 2>&1 > /tmp/log.txt'
COPY postgresql.conf /var/lib/pgsql/11/data/postgresql.conf
COPY pg_hba.conf /var/lib/pgsql/11/data/pg_hba.conf
CMD su postgres -c 'postgres -D /var/lib/pgsql/11/data 2>&1 > /tmp/log.txt'